import { StyleSheet } from 'react-native';

export const logsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  headerSection: {
    backgroundColor: '#fff',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    elevation: 2,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#212121',
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#757575',
    marginTop: 4,
  },
  statsDisplay: {
    flexDirection: 'row',
    gap: 8,
  },
  statBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 4,
  },
  statBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#212121',
  },
  filterContainer: {
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    minHeight: 60,
    maxHeight: 60,
  },
  filterContent: {
    padding: 12,
    gap: 8,
  },
  filterButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: '#f5f5f5',
    marginRight: 4,
  },
  filterButtonActive: {
    backgroundColor: '#2196F3',
  },
  filterButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#757575',
  },
  filterButtonTextActive: {
    color: '#fff',
  },
  eventsList: {
    padding: 12,
  },
  emptyList: {
    flex: 1,
    justifyContent: 'center',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#757575',
    marginTop: 16,
  },
  emptySubtext: {
    fontSize: 13,
    color: '#9E9E9E',
    marginTop: 8,
    textAlign: 'center',
  },
  eventItem: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    alignItems: 'flex-start',
  },
  eventIcon: {
    marginRight: 12,
    marginTop: 2,
  },
  eventContent: {
    flex: 1,
  },
  eventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  eventTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#2196F3',
    flex: 1,
    marginRight: 8,
  },
  eventTime: {
    fontSize: 11,
    color: '#9E9E9E',
    fontWeight: '500',
  },
  eventMessage: {
    fontSize: 13,
    color: '#212121',
    lineHeight: 18,
    marginBottom: 6,
  },
  eventDataContainer: {
    backgroundColor: '#f5f5f5',
    borderRadius: 4,
    padding: 8,
    marginBottom: 4,
  },
  eventDataLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#757575',
    marginBottom: 2,
  },
  eventData: {
    fontSize: 11,
    color: '#616161',
    fontFamily: 'monospace',
    lineHeight: 14,
  },
  eventScreen: {
    fontSize: 10,
    color: '#9E9E9E',
    fontStyle: 'italic',
  },
  eventTypeIndicator: {
    width: 3,
    height: '100%',
    borderRadius: 3,
    marginLeft: 8,
  },
  actionBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    paddingHorizontal: 16,
    paddingVertical: 12,
    elevation: 4,
  },
  actionBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  actionBarText: {
    fontSize: 13,
    color: '#757575',
    fontWeight: '500',
  },
  clearButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#FFEBEE',
    borderRadius: 6,
  },
  clearButtonText: {
    fontSize: 13,
    color: '#F44336',
    fontWeight: '600',
  },
});
